apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: event-booking-system
data:
  # Booking Service
  BOOKING_EVENT_SERVICE_URL: "http://event-service:5002"
  BOOKING_USER_SERVICE_URL: "http://user-service:5004"
  BOOKING_RABBITMQ_URL: "amqp://rabbitmq:5672"
  
  # Event Service
  EVENT_DB_URL: "mongodb://mongodb:27017/eventdb"
  
  # User Service
  USER_DB_URL: "postgresql://postgres:1234@postgres:5432/appdb"
  
  # Notification Service
  NOTIFICATION_DB_URL: "mongodb://mongodb:27017/notifdb"
  NOTIFICATION_RABBITMQ_URL: "amqp://rabbitmq:5672"