apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: event-booking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: your-username/user-service:latest
        ports:
        - containerPort: 5004
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets