apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: event-booking-system
type: Opaque
data:
  JWT_SECRET: "base64-encoded-value"       # echo -n "your-secret" | base64
  POSTGRES_PASSWORD: "MTIzNA=="            # base64 for "1234"
  RABBITMQ_PASSWORD: "Z3Vlc3Q="            # base64 for "guest"