FROM node:23-slim

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev

RUN npm install esbuild@0.25.0 --force

RUN npm i -g serve

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]